# Generated by Django 4.2.1 on 2023-05-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anemia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUsuario', models.CharField(max_length=200)),
                ('genero', models.IntegerField(default=0)),
                ('Hemogobina', models.CharField(max_length=100)),
                ('MCH', models.CharField(max_length=100)),
                ('MCHC', models.CharField(max_length=100)),
                ('MCV', models.CharField(max_length=100)),
                ('Resultado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Diabetes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUsuario', models.CharField(max_length=200)),
                ('genero', models.IntegerField(default=0)),
                ('hipertencion', models.CharField(max_length=100)),
                ('cardiopatia', models.CharField(max_length=100)),
                ('fumador', models.CharField(max_length=100)),
                ('MCI', models.CharField(max_length=100)),
                ('nivelesHemoglobina', models.CharField(max_length=100)),
                ('nivelGlucosa', models.CharField(max_length=100)),
                ('edad', models.IntegerField(default=0)),
                ('resultado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('technology', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
