# Generated by Django 4.2.1 on 2023-06-09 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('correoElectronico', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
                ('edad', models.IntegerField()),
                ('peso', models.FloatField()),
                ('altura', models.FloatField()),
                ('direccion', models.CharField(max_length=200)),
                ('numero_celular', models.CharField(max_length=20, unique=True)),
                ('ci', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('technology', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correoElectronico', models.EmailField(max_length=254, unique=True)),
                ('numero_celular', models.CharField(max_length=20, unique=True)),
                ('ci', models.CharField(max_length=20, unique=True)),
                ('especialidad', models.CharField(max_length=100)),
                ('rol', models.CharField(max_length=100)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.hospital')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Diabetes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.IntegerField(default=0)),
                ('hipertencion', models.CharField(max_length=100)),
                ('cardiopatia', models.CharField(max_length=100)),
                ('fumador', models.CharField(max_length=100)),
                ('MCI', models.CharField(max_length=100)),
                ('nivelesHemoglobina', models.CharField(max_length=100)),
                ('nivelGlucosa', models.CharField(max_length=100)),
                ('edad', models.IntegerField(default=0)),
                ('resultado', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.medico')),
                ('pacientepaciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='CancerPulmonar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.IntegerField()),
                ('Genero', models.IntegerField()),
                ('ConsumoAlcohol', models.IntegerField()),
                ('AlergiaPolvo', models.IntegerField()),
                ('RegistroGenetico', models.IntegerField()),
                ('EnfermedadPulmonar', models.IntegerField()),
                ('DietaEquilibrada', models.IntegerField()),
                ('Obesidad', models.IntegerField()),
                ('Tabaquismo', models.IntegerField()),
                ('FumadorPasivo', models.IntegerField()),
                ('DolorPecho', models.IntegerField()),
                ('TosConSangre', models.IntegerField()),
                ('fatiga', models.IntegerField()),
                ('PerdidaPeso', models.IntegerField()),
                ('DificultadRespirar', models.IntegerField()),
                ('Sibilancia', models.IntegerField()),
                ('DificultadTragar', models.IntegerField()),
                ('TosSeca', models.IntegerField()),
                ('resultados', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.medico')),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Anemia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.IntegerField(default=0)),
                ('Hemogobina', models.CharField(max_length=100)),
                ('MCH', models.CharField(max_length=100)),
                ('MCHC', models.CharField(max_length=100)),
                ('MCV', models.CharField(max_length=100)),
                ('Resultado', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.medico')),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.paciente')),
            ],
        ),
    ]
