# Generated by Django 4.2.1 on 2023-05-29 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='HistorialPaciente',
            unique_together={('paciente', 'anemia', 'diabetes', 'cancer_pulmonar')},
        ),
        migrations.CreateModel(
            name='AsignacionMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField()),
                ('historial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.historialpaciente')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.medico')),
            ],
            options={
                'verbose_name_plural': 'Asignaciones Médicas',
                'unique_together': {('historial',)},
            },
        ),
    ]
