# Generated by Django 4.2.1 on 2023-05-17 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancerPulmonar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.IntegerField()),
                ('Genero', models.IntegerField()),
                ('ConsumoAlcohol', models.IntegerField()),
                ('AlergioPolvo', models.IntegerField()),
                ('RegistroGenetico', models.IntegerField()),
                ('EnfermedadPulmonar', models.IntegerField()),
                ('DietaEquilibrada', models.IntegerField()),
                ('Obesidad', models.IntegerField()),
                ('Tabaquismo', models.IntegerField()),
                ('fumadorPasico', models.IntegerField()),
                ('DolorPecho', models.IntegerField()),
                ('TosConSangre', models.IntegerField()),
                ('fatiga', models.IntegerField()),
                ('PerdidaPeso', models.IntegerField()),
                ('DificultadRespirar', models.IntegerField()),
                ('Sibilancia', models.IntegerField()),
                ('DificultadTragar', models.IntegerField()),
                ('TosSeca', models.IntegerField()),
                ('resultados', models.CharField(max_length=100)),
            ],
        ),
    ]
