# Generated by Django 4.2.1 on 2023-05-15 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anemia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUsuario', models.CharField(max_length=200)),
                ('Hemogobina', models.CharField(max_length=100)),
                ('MCH', models.CharField(max_length=100)),
                ('MCHC', models.CharField(max_length=100)),
                ('MCV', models.CharField(max_length=100)),
                ('Resultado', models.CharField(max_length=100)),
            ],
        ),
    ]
