# Generated by Django 4.2.1 on 2023-05-17 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_cancerpulmonar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cancerpulmonar',
            old_name='AlergioPolvo',
            new_name='AlergiaPolvo',
        ),
        migrations.RenameField(
            model_name='cancerpulmonar',
            old_name='fumadorPasico',
            new_name='FumadorPasivo',
        ),
    ]
