# Generated by Django 4.2.1 on 2023-05-17 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_cancerpulmonar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancerpulmonar',
            name='AlergioPolvo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cancerpulmonar',
            name='ConsumoAlcohol',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cancerpulmonar',
            name='DietaEquilibrada',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cancerpulmonar',
            name='DificultadRespirar',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cancerpulmonar',
            name='DificultadTragar',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cancerpulmonar',
            name='DolorPecho',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cancerpulmonar',
            name='EnfermedadPulmonar',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cancerpulmonar',
            name='Genero',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cancerpulmonar',
            name='Obesidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cancerpulmonar',
            name='PerdidaPeso',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cancerpulmonar',
            name='RegistroGenetico',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cancerpulmonar',
            name='Sibilancia',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cancerpulmonar',
            name='Tabaquismo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cancerpulmonar',
            name='TosConSangre',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cancerpulmonar',
            name='TosSeca',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cancerpulmonar',
            name='edad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cancerpulmonar',
            name='fatiga',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cancerpulmonar',
            name='fumadorPasico',
            field=models.IntegerField(),
        ),
    ]
