# Generated by Django 4.2.1 on 2023-05-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_alergiopolvo_cancerpulmonar_alergiapolvo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancerpulmonar',
            name='nombreUsuario',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
