# Generated by Django 4.2.1 on 2023-06-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_cancerpulmonar_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancerpulmonar',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
