# Generated by Django 4.2.1 on 2023-06-15 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_cancerpulmonar_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.hospital'),
        ),
    ]
